name: OWASP ZAP Scan

on:
  workflow_dispatch:  
  push:
    branches: [ test ]

jobs:
  dast:
    name: Dynamic App Security Testing (ZAP Baseline)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set script permission
        run: chmod +x scripts/zap-script.sh

      - name: Run ZAP Baseline Scan
        run: scripts/zap-script.sh

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_baseline_report.html